#!/bin/bash
set -e
trap 'echo "ERROR: El comando [$BASH_COMMAND] falló en la línea $LINENO"' ERR

sudo apt update && sudo apt upgrade -y

#sudo apt-get install -y postgresql-14

#read -s -p "Contraseña para el usuario canvas: " DB_PASS
#echo  
#sudo -u postgres psql -c "CREATE USER canvas WITH PASSWORD '$DB_PASS' NOCREATEDB NOSUPERUSER NOCREATEROLE;"
#sudo -u postgres createdb canvas_production --owner=canvas
#sudo apt-get install git-core

#sudo mkdir -p /var/canvas
#sudo chown -R $USER /var/canvas

#git clone https://gitlab.espol.edu.ec/uvs/explora/explora2025v3.git /var/canvas

cd /var/canvas
ls
#sudo apt-get install software-properties-common

#sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
#sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1

#sudo mkdir -p /etc/apt/keyrings
#gpg --no-default-keyring --keyring /tmp/temp-keyring.gpg --keyserver keyserver.ubuntu.com --recv-keys 9CD72EB52048A870
#gpg --no-default-keyring --keyring /tmp/temp-keyring.gpg --export 9CD72EB52048A870 | sudo tee /etc/apt/keyrings/instructure-ruby.gpg > /dev/null

#echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/instructure-ruby.gpg] https://ppa.launchpadcontent.net/instructure/ruby/ubuntu jammy main" | sudo tee /etc/apt/sources.list.d/instructure-ruby.list



#sudo apt-get update
#apt-cache policy ruby3.1 ruby3.2 ruby3.4



#sudo apt-get -y install ruby3.4 ruby3.4-dev zlib1g-dev libxml2-dev \
#                     libsqlite3-dev postgresql libpq-dev \
#                     libxmlsec1-dev libyaml-dev libidn11-dev curl make g++
#curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
#sudo apt-get install -y nodejs
#sudo npm install -g npm@latest


#sudo gem install bundler
#bundle config set --local path vendor/bundle
#bundle install

#sudo npm -g install yarn
#yarn install

#for config in amazon_s3 database vault_contents \
#  delayed_jobs domain file_store outgoing_mail security external_migration; \
#  do cp config/$config.yml.example config/$config.yml; done


#cp config/dynamic_settings.yml.example config/dynamic_settings.yml
#nano config/dynamic_settings.yml

#cp config/database.yml.example config/database.yml
#nano config/database.yml

#cp config/outgoing_mail.yml.example config/outgoing_mail.yml
#nano config/outgoing_mail.yml

#cp config/domain.yml.example config/domain.yml
#nano config/domain.yml

#cp config/security.yml.example config/security.yml
#nano config/security.yml

#yarn gulp rev
#RAILS_ENV=production bundle exec rake db:initial_setup

#cd /var/canvas

#sudo adduser --disabled-password --gecos canvas canvasuser

#mkdir -p log tmp/pids public/assets app/stylesheets/brandable_css_brands
#touch app/stylesheets/_brandable_variables_defaults_autogenerated.scss
#touch Gemfile.lock
#touch log/production.log
#sudo chown -R canvasuser config/environment.rb log tmp public/assets \
#                         app/stylesheets/_brandable_variables_defaults_autogenerated.scss \
#                         app/stylesheets/brandable_css_brands Gemfile.lock config.ru


#esto sirve para ruby 3.3, por testeo se esta usando 3.4, pero aun asi podrian haber errroes con migraciones relacionados a frozen
#RAILS_ENV=production CANVAS_BUILD_CONCURRENCY=1 bundle exec rake canvas:compile_assets 2>&1 | tee /tmp/log_compilacion.txt

# Definimos el entorno
#export RAILS_ENV=production

#echo "Iniciando compilación manual para evitar error de Ruby 3.4..."

#bundle exec rake js:yarn_install
#bundle exec rake css:styleguide
#bundle exec rake i18n:generate_js
#bundle exec rake js:gulp_rev
#bundle exec rake brand_configs:write
#bundle exec rake css:compile
#bundle exec rake js:webpack_production

#RAILS_ENV=production CANVAS_BUILD_CONCURRENCY=1 bundle exec rake brand_configs:generate_and_upload_all
#sudo chown -R canvasuser public/dist/brandable_css


#sudo chown canvasuser config/*.yml
#sudo chmod 400 config/*.yml

#sudo apt-get install apache2

# Install our PGP key and add HTTPS support for APT
#sudo apt-get install -y dirmngr gnupg apt-transport-https ca-certificates curl

#curl https://oss-binaries.phusionpassenger.com/auto-software-signing-gpg-key.txt | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/phusion.gpg >/dev/null

# Add our APT repository
#sudo sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger jammy main > /etc/apt/sources.list.d/passenger.list'
#sudo apt-get update

# Install Passenger + Apache module
#sudo apt-get install -y libapache2-mod-passenger

#sudo a2enmod passenger
#sudo apache2ctl restart

#sudo /usr/bin/passenger-config validate-install

#sudo a2enmod rewrite
#sudo a2enmod passenger
#sudo systemctl restart apache2

# Reemplazo de: sudo unlink /etc/apache2/sites-enabled/000-default.conf
#sudo a2dissite 000-default
#sudo nano /etc/apache2/sites-available/canvas.conf

#se salta ssl por facilidad
#sudo apt-get install libapache2-mod-xsendfile
#sudo apachectl -M | sort

#sudo nano /var/canvas/config/environments/production-local.rb
#sudo chmod 400 /var/canvas/config/environments/production-local.rb
#sudo add-apt-repository -y ppa:redislabs/redis

#sudo apt-get install -y redis-server
#cd /var/canvas/
#sudo cp config/cache_store.yml.example config/cache_store.yml
#sudo nano config/cache_store.yml
#sudo chown canvasuser config/cache_store.yml
#sudo chmod 400 config/cache_store.yml

#sudo cp config/redis.yml.example config/redis.yml
#sudo nano config/redis.yml
#sudo chown canvasuser config/redis.yml
#sudo chmod 400 config/redis.yml

#qty aun no se usa, se ha saltado

#sudo chown -R canvasuser:canvasuser /var/canvas
# Les damos permiso de lectura al dueño (que ahora es canvasuser)
#sudo chmod 600 /var/canvas/config/*.yml
#sudo chmod 600 /var/canvas/config/environments/production-local.rb
#sudo chmod -R 755 /var/canvas/tmp /var/canvas/log /var/canvas/public/assets
